name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npm install
      - run: npm run lint

      - name: Build storybook and deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm ci
          build_command: npm run build-storybook
          path: dist/storybook
          checkout: false
