name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          version: 18.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Build Prod
        run: npm run build

      - name: Build storybook and deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: yarn install
          build_command: yarn build-storybook
          path: dist/storybook
          checkout: true
