name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install deps and build (with cache)
      uses: bahmutov/npm-install@v1
    - name: Lint
      run: npm run lint
    - name: Build Prod
      run: npm run build
    - name: Build storybook and deploy
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        install_command: yarn install
        build_command: yarn build-storybook
        path: dist/storybook
        checkout: true
